services:
  main:
    image: ubuntu
    platform: linux/amd64
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    entrypoint: '/bin/sh -c "sleep infinity"'

  postgres:
    image: postgres:15
    command:
    -  "postgres"
    -  "-cshared_preload_libraries=pg_stat_statements"
    network_mode: service:main
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ../devdata/postgres:/var/lib/postgresql/data